apiVersion: apps/v1
kind: Deployment
metadata:
  name: acmeair-mainservice-quarkus-native
spec:
  replicas: 1
  selector:
    matchLabels:
      name: acmeair-main-deployment
  template:
    metadata:
      annotations:
        prometheus.io/port: '9080'
        prometheus.io/scrape: 'true'
      labels:
        name: acmeair-main-deployment
    spec:
      containers:
      - env:
        image: <YourImageRepository>/acmeair-mainservice-quarkus:native
        imagePullPolicy: Always
        name: acmeair-mainservice-quarkus-native
        ports:
        - containerPort: 9080
        - containerPort: 9443
---
apiVersion: v1
kind: Service
metadata:
  name: acmeair-mainservice-quarkus
spec:
  ports:
  - port: 9080
  selector:
    name: acmeair-main-deployment
