apiVersion: apps/v1
kind: Deployment
metadata:
  name: acmeair-nginx-deployment
spec:
  minReadySeconds: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: acmeair-nginx-deployment
  template:
    metadata:
      annotations:
        prometheus.io/port: '80'
        prometheus.io/scrape: 'true'
      labels:
        name: acmeair-nginx-deployment
    spec:
      containers:
      - image: <YourImageRepository>/acmeair-nginx
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 90Mi
      terminationGracePeriodSeconds: 300
---
apiVersion: v1
kind: Service
metadata:
  name: acmeair-nginx-service
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    name: acmeair-nginx-deployment
