apiVersion: apps/v1
kind: Deployment
metadata:
  name: acmeair-customerservice-quarkus-jvm
spec:
  replicas: 1
  selector:
    matchLabels:
      name: acmeair-customer-deployment
  template:
    metadata:
      annotations:
        prometheus.io/port: '9080'
        prometheus.io/scrape: 'true'
      labels:
        name: acmeair-customer-deployment
    spec:
      containers:
      - env:
        - name: MONGO_HOST
          value: acmeair-customer-db
        - name: SECURE_SERVICE_CALLS
          value: 'true'
        image: <YourImageRepository>/acmeair-customerservice-quarkus:jvm
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /q/health/live
            port: 9080
          initialDelaySeconds: 120
          periodSeconds: 15
        name: acmeair-customerservice-quarkus-jvm
        ports:
        - containerPort: 9080
        - containerPort: 9443
        readinessProbe:
          httpGet:
            path: /q/health/ready
            port: 9080
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: acmeair-customerservice-quarkus
spec:
  ports:
  - port: 9080
  selector:
    name: acmeair-customer-deployment
