FROM registry.access.redhat.com/ubi8/ubi-minimal:8.5

ARG JAVA_PACKAGE=java-11-openjdk-headless

ARG JMETER_VERSION=apache-jmeter-5.4.1
ARG JMETER_PACKAGE_URL=https://archive.apache.org/dist/jmeter/binaries/${JMETER_VERSION}.tgz

WORKDIR /deployments

RUN microdnf install ${JAVA_PACKAGE} curl tar gzip rsync less \
    && microdnf update \
    && microdnf clean all \
    && chmod "g+rwX" /deployments \
    && curl -s ${JMETER_PACKAGE_URL} | tar -xzf - \
    && chown -R 1001:root /deployments

COPY --chown=1001:root acmeair-jmeter-2.0.0-SNAPSHOT.jar json-simple-1.1.1.jar ${JMETER_VERSION}/lib/ext/
COPY --chown=1001:root acmeair-jmeter/scripts/AcmeAir-microservices-mpJwt.jmx acmeair-jmeter/scripts/*.csv scripts/
COPY --chown=1001:root docker/driver.sh ./

ENV JRE_HOME=/usr/lib/jvm/jre-11-openjdk
ENV JMETER_HOME=/deployments/${JMETER_VERSION}
ENV TZ=UTC LANG=C

ENV HOST=localhost
ENV PORT=80
ENV THREADS=1
ENV DURATION=60
ENV SUMMARY_INTERVAL=10
ENV LOG_RESPONSE=

USER 1001

ENTRYPOINT [ "./driver.sh" ]
